# Generated by Django 6.0.5 on 2026-05-28 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('technical_proposal', models.TextField()),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='bid_documents/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_EVALUATION', 'Under Evaluation'), ('AWARDED', 'Awarded'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='procurements.procurement')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('procurement', 'submitted_by')},
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('awarded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards_made', to=settings.AUTH_USER_MODEL)),
                ('procurement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='award', to='procurements.procurement')),
                ('winning_bid', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='award', to='bids.bid')),
            ],
        ),
    ]
